import assert from "node:assert/strict";
import test, { after } from "node:test";
import { register } from "tsx/esm/api";
const unregister = register();
after(unregister);
const { FixedStepLoop } = await import("../src/core/FixedStepLoop.ts");

test("expensive physics yields after one fixed step and accounts for dropped catch-up time", t => {
  let callback;
  let clock = 0;
  const timesteps = [];
  let renders = 0;
  t.mock.method(performance, "now", () => clock);
  const oldRaf = globalThis.requestAnimationFrame;
  const oldCancel = globalThis.cancelAnimationFrame;
  globalThis.requestAnimationFrame = fn => { callback = fn; return 1; };
  globalThis.cancelAnimationFrame = () => {};
  const loop = new FixedStepLoop(dt => { timesteps.push(dt); clock += 30; }, () => renders++);
  t.after(() => { loop.stop(); globalThis.requestAnimationFrame = oldRaf; globalThis.cancelAnimationFrame = oldCancel; });
  loop.start();
  callback(0);
  callback(100);
  assert.deepEqual(timesteps, [1 / 60]);
  assert.equal(renders, 2);
  assert.ok(loop.stats().droppedTimeMs > 65);
  assert.equal(loop.stats().activeWallTimeS, .1);
  assert.equal(loop.stats().simulatedTimeS, 1 / 60);
  assert.ok(Math.abs(loop.stats().realtimeRatio - 1 / 6) < 1e-12);
  callback(1100);
  assert.ok(loop.stats().droppedTimeMs > 1000, 'include time discarded by the frame clamp');
  assert.equal(loop.stats().activeWallTimeS, 1.1);
  loop.pause();
  callback(2100);
  assert.equal(timesteps.length, 2);
  assert.equal(renders, 4);
  assert.equal(loop.stats().activeWallTimeS, 1.1, 'paused time is excluded');
  loop.resume();
  callback(3100);
  assert.equal(loop.stats().activeWallTimeS, 1.1, 'resume establishes a fresh wall-clock origin');
  loop.resetTiming();
  assert.equal(loop.stats().simulatedTimeS, 0);
  assert.equal(loop.stats().activeWallTimeS, 0);
  assert.equal(loop.stats().realtimeRatio, 0);
});
